plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version "${moddevgradle_version}"
    id "me.modmuss50.mod-publish-plugin" version "2.+"
}

version = "mc${archive_minecraft_version}-NeoForge-${mod_version}"
group = project.maven_group
var realVersion = project.mod_version + '+neoforge'

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        url = "https://maven.architectury.dev/"
        content {
            includeGroup "dev.architectury"
        }
    }
    maven {
        url = "https://maven.shedaniel.me/"
        content {
            includeGroup "me.shedaniel"
            includeGroup "me.shedaniel.cloth"
        }
    }
    maven {
        url = "https://maven.blamejared.com/"
        content {
            includeGroup "me.shedaniel"
            includeGroup "me.shedaniel.cloth"
        }
    }
    maven {
        url = "https://maven.parchmentmc.org"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    implementation "me.shedaniel:RoughlyEnoughItems-neoforge:${project.rei_version}"
}

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

processResources {
    inputs.property "version", realVersion
    inputs.property "neo_version_range", project.neo_version_range

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": realVersion, "neo_version_range": project.neo_version_range
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    exclude '**/*.py'
    exclude 'fabric.mod.json'
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

publishMods {
    file = jar.archiveFile
    changelog = file('CHANGELOG.md').exists() ? file('CHANGELOG.md').text : ''
    type = ['release': STABLE, 'beta': BETA, 'alpha': ALPHA][release_type]
    modLoaders.add("neoforge")
    displayName = "[NeoForge ${supported_version}] ${mod_version}"
    version = realVersion

    curseforge {
        projectId = "827792"
        client = true
        server = true
        accessToken = providers.environmentVariable("CURSE_TOKEN")
        minecraftVersions.add(minecraft_version)
        minecraftVersions.add("26.1")
        minecraftVersions.add("26.1.1")
        requires("roughly-enough-items")
    }
    modrinth {
        projectId = "5ipLgHDs"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
        minecraftVersions.add("26.1")
        minecraftVersions.add("26.1.1")
        requires("rei")
    }
}
