org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en
org.gradle.daemon=false
# org.gradle.java.home=D:/Program Files/Eclipse Foundation/jdk-17.0.1.12-hotspot
# NeoForge Properties
minecraft_version=1.21.1
supported_version=1.21.1
loader_version=21.1.235
loader_version_range=[4,)
neoforge_version_range=[21.1,)
minecraft_version_range=[1.21,1.22)
# Mod Properties
mod_version=3.0.0
release_type=release
mod_id=rei_custom_command
maven_group=snownee.rei_custom_command
archives_base_name=REICustomCommand
# Dependencies
cloth_config_version=15.0.140
rei_version=16.0.799
rei_version_range=[16.0.799,)
jei_version=19.27.0.346
