modLoader="javafml"
loaderVersion="[1,)"
license="ARR"
issueTrackerURL="https://github.com/Snownee/REICustomCommand/issues"

[[mods]]
modId="rei_custom_command"
version="${version}"
displayName="REI Custom Command"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rei-custom-command"
authors="Snownee"
description='''Allows you to create custom commands into REI favorites'''

[[mixins]]
config="rei_custom_command.mixins.json"

[[dependencies.rei_custom_command]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.rei_custom_command]]
modId="roughlyenoughitems"
type="required"
versionRange="[26.1.819,)"
ordering="NONE"
side="CLIENT"

[[dependencies.rei_custom_command]]
modId="minecraft"
type="required"
versionRange="[26,)"
ordering="NONE"
side="BOTH"

[modproperties.rei_custom_command]
catalogueItemIcon="minecraft:command_block"
configuredBackground="minecraft:textures/block/command_block_front.png"
"modmenu.discord"="https://discord.gg/rRBvGkz"
"modmenu.donate"="https://ko-fi.com/snownee"
