modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "ARR"
issueTrackerURL = "https://github.com/Snownee/REICustomCommand/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "REI Custom Command"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/rei-custom-command"
authors = "Snownee"
description = '''Allows you to create custom commands into REI favorites'''

[[mixins]]
config = "rei_custom_command.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "roughlyenoughitems"
type = "required"
versionRange = "${rei_version_range}"
ordering = "NONE"
side = "CLIENT"
